title: Blog Title
email: contact@example.com
author: Blog Author
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: ""
url: ""

paginate: 2
more: "read more »"
excerpt_separator: "\n\n" #  one blank line
permalink: pretty

navigation:
  - about.md
  - archive.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

style:
  body: 'white' # main background color
  padding: 2 # factor for the padding width
  articles: 'light' # 'light' 'dark' and 'stripe' possible
  nav: "#222" # color of the header and footer
  uppercase: true # use uppercase text for headings
  margin: 0% # increase to add a margin to the left and right side
  margincolor: "#f0f0f0" # only relevant if margin is non-zero

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/me/", square: true}
  - reddit: {url: "https://www.reddit.com/user/me/", square: true}
  - twitter: {url: "https://twitter.com/me/", square: true}
  - facebook: {url: "https://www.facebook.com/me", square: true}
  - google-plus: {url: "https://plus.google.com/+me", square: true}
  - youtube: {url: "https://www.youtube.com/user/me", square: true}
  - tumblr: {url: "http://me.tumblr.com/", square: true}
  - steam: {url: "http://steamcommunity.com/id/me/", square: true}

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
